# This is a generated file. Not intended for manual editing.
services:
  faculty-service-tel:
    build:
      context: "/home/PNguyen/Workspace/MyProject/distributed_student_management_system/src"
      dockerfile: "./FacultyService/Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/FacultyService.Api.dll"
    environment: {}
    image: "facultyservice.api:dev"
    ports: []
    volumes:
    - "/home/PNguyen/Workspace/MyProject/distributed_student_management_system/src/FacultyService/FacultyService.Api:/app:rw"
    - "/home/PNguyen/Workspace/MyProject/distributed_student_management_system:/src:rw"
    - "/home/PNguyen/.nuget/packages:/root/.nuget/packages"
    working_dir: "/app"
